version: "3.4"

volumes:
  db-data:

services:
  nginx:
    restart: always
    image: nginx
    container_name: nuxt-django-postgresql.nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./backend/static:/static
    depends_on:
      - django

  postgresql:
    build:
      context: ./db
    container_name: nuxt-django-postgresql.postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "mysite"
      POSTGRES_USER: "mysiteuser"
      POSTGRES_PASSWORD: "mysitepass"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: nuxt-django-postgresql.adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  django:
    restart: always
    build:
      context: ./backend
    image: nuxt-django-postgresql-django
    container_name: nuxt-django-postgresql.django
    volumes:
      - ./backend:/app
    expose:
      - "8001"
    depends_on:
      - postgresql
      - rabbitmq
    command: bash -c "uwsgi --socket :8001 --module mysite.wsgi"

  rabbitmq:
    container_name: nuxt-django-postgresql.rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672

  celery:
    image: nuxt-django-postgresql-django
    container_name: nuxt-django-postgresql.celery
    volumes:
      - ./backend:/app
    depends_on:
      - django
    command: bash -c "celery -A mysite worker -l info"

  celery-beat:
    image: nuxt-django-postgresql-django
    container_name: nuxt-django-postgresql.celery-beat
    volumes:
      - ./backend:/app
    depends_on:
      - django
    command: bash -c "celery -A mysite beat -l info"

  nuxt:
    build:
      context: ./frontend
    container_name: nuxt-django-postgresql.nuxt
    volumes:
      - ./frontend/nuxt:/app
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      - django
    tty: true
    command: bash -c "yarn install && yarn dev -o"
