version: '3.4'

volumes:
  db-data:

services:
  nginx:
    restart: always
    image: nginx
    container_name: nuxt_django_postgresql.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./backend/static:/static
    depends_on:
      - django

  postgresql:
    build:
      context: ./db
    container_name: nuxt_django_postgresql.postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mysite"
      POSTGRES_USER: "mysiteuser"
      POSTGRES_PASSWORD: "mysitepass"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: nuxt_django_postgresql.adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  django:
    restart: always
    build:
      context: ./backend
    container_name: nuxt_django_postgresql.django
    volumes:
      - ./backend:/app
    expose:
      - "8001"
    depends_on:
      - postgresql
    command: uwsgi --socket :8001 --module mysite.wsgi

  nuxt:
    build:
      context: ./frontend
    container_name: nuxt_django_postgresql.nuxt
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    command: bash -c "yarn install && npm run dev"
